// src/data.js
const data = [

  {
    id: 28,
    title: 'Tip Hub',
    category: 'Donation',
    image: '/images/tiphub.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'eFeePayment ® is an application to make the payment to school by the parents. This application helps to keep the track of payment by the parents and the schools as well. Using this application, a fee of school can be paid in few easy steps.',
  },
  {
    id: 1,
    title: 'Pickbox',
    category: 'Streaming',
    image: '/images/picbox.png',
    technology: 'Bootstrap, CSS3, AngularJs UI',
    description: 'Pickbox is a streaming service offering more than 3000 hours of exclusive premieres, hit series, movies and animated features.Watch them anywhere and anytime. All you need is a device and internet connection....',
  },
  {
    id: 2,
    title: 'Moviboo',
    category: 'Streaming',
    image: '/images/movibo.png',
    technology: 'PSD Designing, Bootstrap, CSS3, AngularJs UI',
    description: 'Moovibo is a streaming service offering more than 3000 hours of exclusive premieres, hit series, movies and animated features. Watch them anywhere and anytime. All you need is a device and internet connection.',
  },
  {
    id: 3,
    title: 'Pow Wow',
    category: 'Streaming',
    image: '/images/pow-wow.png',
    technology: 'PSD Designing, Bootstrap, HTML5, CSS3',
    description: 'Pow Wow is a Video Streaming OTT Platform.',
  },
  {
    id: 4,
    title: 'Can Do Better',
    category: 'Datting',
    image: '/images/candoBetter.png',
    technology: 'PSD Designing, Bootstrap, HTML5, CSS3',
    description: 'CanDoBetter is the premier matching portal that allows the world to decide who "Can Do Better". The website allows couples who think they can find a better-looking partner to be rated and to connect to others so they "Can Do Better". Features : Dating, Rating, Virtual Gifts, Social Internal Networking Tools, Send Receive Messages, Facebook Connectivity ',
  },
  {
    id: 5,
    title: 'Click-Enforcer',
    category: 'Information',
    image: '/images/click-enforcer.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Click Inforser is a practice of repeadly Clicking on an advertisement hosted on a website with the intention of generating revenue for the host website or draining revenue from the advertiser. Alarming, the future forecasts for click fraud is not great and is on the rise!! with the world in economic crisis and global recessions looming competition is becoming more and more fierce as businesses fight to stay operational. unfortunately many of your competitors are resorting to desperate black hand tactics with the intent to drive up your cost and reduce competition',
  },
  {
    id: 6,
    title: 'BlastofBeauty',
    category: 'E-Commerce',
    image: '/images/blastofbeauty.png',
    technology: 'HTML5 / CSS3',
    description: 'They will provide the professional salon industry with innovative exclusive products, available and sold only in salons. Says Frank Commisso co-owner of Blast of Beauty.',
  },
  {
    id: 7,
    title: 'eFeePayment',
    category: 'Information',
    image: '/images/efeepayment.png',
    technology: 'HTML5 / CSS3',
    description: 'eFeePayment ® is an application to make the payment to school by the parents. This application helps to keep the track of payment by the parents and the schools as well. Using this application, a fee of school can be paid in few easy steps.        ',
  },
  {
    id: 8,
    title: 'future Music',
    category: 'E-Commerce',
    image: '/images/futureMusic.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Future Music Australia was established in 1998 to professionally service the needs of the music education sector. This website is designed to showcase the products we offer and make ordering easier, but as a dedicated school supplier we understand that every school’s ordering process is different',
  },
  {
    id: 9,
    title: 'Get Snatchr',
    category: 'E-Commerce',
    image: '/images/getSnatchr.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Al Mushrif Oilfield Supplies and Services has dedicated its future in innovating the industry with the best quality products and services. With our dedicated appropriate teams to ensure satisfaction along with complete business experience.        ',
  },
  {
    id: 10,
    title: 'Guardian',
    category: 'Banking',
    image: '/images/guardian.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Guardian Vaults is Australia’s largest privately owned safe custody facility independent of the banking system and financial institutions. For more than a decade, Guardian Vaults has been the leading provider for safe deposit boxes and allocated bullion storage, and remains Australian’s first choice. As the first of its kind in Australia to ever open, Guardian Vaults set the standard and tone to be the highest quality in security available to clients. With facilities in Melbourne and Sydney CBD and an unblemished reputation; our unique offering of gold and silver procurement, secure storage and insurance, Guardian Vaults provides you with a solution not offered by anyone else. The team at Guardian Vaults are committed to conducting business with honesty, respect, integrity and professionalism.',
  },
  {
    id: 11,
    title: 'Hub',
    category: 'E-Commerce',
    image: '/images/hub.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Division of Italian Food & Beverage an American company publicly trading on the OTC Market under the Symbol IFBC in its joint venture with www.idbeveragegroup.com an American company founded in 2009 by a group of wine lovers with a passion for artisanal wineries to the attention of the US markets, and with a growing portfolio of distinct wines from Italy and Argentina, IFBC-HUB USA goal is to expend in the US through the “idbeveragegroup” established clientele in the US.        ',
  },
  {
    id: 12,
    title: 'IFBCORP',
    category: 'Information',
    image: '/images/ifbc.png',
    technology: 'Wordpress, HTML5, CSS3',
    description: 'Italian Food & Beverage Corp (IFBC) is an importer of fine food and beverages which are derived from the renowned Italian wine and food culture. IFBC is now purveying a new energy drink (DINO), which is made in Italy. This delicious, healthful, energizing refresher is distinguished from its more well-known competitors by its decided non-metallic after taste, and its mere trace of unhealthy Taurine which is abundant in most other energy drinks. Currently, IFBC is gearing up for the future importation of fine Italian wine in cans, produced by the same Italian manufacturer as the (DINO)energy drink.        ',
  },
  {
    id: 13,
    title: 'Joule & Jouly',
    category: 'E-Commerce',
    image: '/images/joule&jouly.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Ecommerce Website for the Woman Cloths',
  },
  {
    id: 14,
    title: 'LodestoneVoting',
    category: 'Information',
    image: '/images/lodestonevoting.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Lodestone Helps Voters Lodestone Voting was developed in response to one of the most difficult challenges facing voters today. Namely, after tens of millions of dollars spent in advertising in each state for each election cycle, the average person knows little, if anything, about the candidates running for office. The easy races are the big ones – President, Governor, US Senator, Congress…but after them it becomes very difficult to know much about anyone running for office. Lodestone cuts through all the noise, and gets right to the heart of the matter, and answers the question, “Who should I vote for?” in each election, for each office, regardless of personality or issues at stake. Lodestone is the first generation in smart voting, where intelligence is crowd sourced, and an accurate sample ballot is created for each individual voter, perfectly tailored to their own unique political beliefs and principals.',
  },
  {
    id: 15,
    title: 'RealtyBuzz',
    category: 'Information',
    image: '/images/realtyBuzz.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: '99acres brings to you exclusive webinars and industry insights providing a glimpse into what is buzzing in the real estate market. Know what industry stalwarts have to say about emerging trends and developments in the Indian Real Estate sector. Hear their perspective on consumer queries, and on the property market, in general.',
  },
  {
    id: 16,
    title: 'Scuderiaf1',
    category: 'E-Commerce',
    image: '/images/scuderiaf1.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Cars are the most common type of transportation in Kuwait. Scuderia F1 is a private automotive servicing company based in Kuwait since decades, specialized in serving a unique segment of vehicles hence customers. Known by its problem-solving ability, high-quality spare parts, a smooth process, and superior functionality.',
  },
  {
    id: 17,
    title: 'SupplementHunt',
    category: 'E-Commerce',
    image: '/images/supplementhunt.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Online Ecommerce Platform of Supplement',
  },
  {
    id: 18,
    title: 'Fresh House',
    category: 'Information',
    image: '/images/freshhouse.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Online Lunch Delivery Food App ',
  },
  {
    id: 19,
    title: 'Parts2Door',
    category: 'E-Commerce',
    image: '/images/parts2door.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Online Selling of Cars Parts',
  },
  {
    id: 20,
    title: 'TrackPMO',
    category: 'Information',
    image: '/images/trackpmo.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Track PMO offers a comprehensive solution of technology and services designed to generate high impact very quickly in the service provider organizations. We are currently working with global organizations that seek to achieve high levels of excellence in the provision of their services. Track PMO increases profit margins and cash flow in the implementation of its Services, improving the implementation of its services,improving the estimate, reducing risks and waste,reducing the loss of income, reducing billing cycles, reducing the need to discount the value of services and maximizing the use of resources.        ',
  },
  {
    id: 21,
    title: 'Early Edge',
    category: 'Information',
    image: '/images/earlyEdge.png',
    technology: 'AngularJs UI, HTML5, SCSS',
    description: 'Online Learning Platform',
  },
  {
    id: 22,
    title: 'Socialyse.Biz',
    category: 'Information',
    image: '/images/socialyse.biz.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Social Media Management App',
  },
  {
    id: 23,
    title: 'RadiologyRachana',
    category: 'Information',
    image: '/images/radiologiest.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'Doctor Appointment App ',
  },
  {
    id: 24,
    title: 'Clavo',
    category: 'Information',
    image: '/images/clavo.png',
    technology: 'HTML5, CSS3',
    description: 'Modern. Organic. Beautiful. Re-imagine you with the touch of organic perfection & glamourous exquisiteness. Let nature shine your beauty with state-of-the-art products, carved to make you shine till eternity. Revered around the world, all our products depict a promise of safety, qualitative commitment & sheer nourishment. Our organic editions are PETA certified and raw materials are exclusively sourced from the USA & UK. Shake hands with the real you with Clavo!        ',
  },
  {
    id: 25,
    title: 'Divija',
    category: 'E-Commerce',
    image: '/images/divija.png',
    technology: ' HTML5, CSS3',
    description: 'Divish Aurum is established in 2018 in New Delhi. Today, it has a strong retail network of over outlets spread across countries, wholesale units in addition to offices, design centers and factories spread across India.        ',
  },
  {
    id: 26,
    title: 'Score Card',
    category: 'Information',
    image: '/images/scoreCard.png',
    technology: ' HTML5, CSS3',
    description: 'Divish Aurum is established in 2018 in New Delhi. Today, it has a strong retail network of over outlets spread across countries, wholesale units in addition to offices, design centers and factories spread across India.        ',
  },
  {
    id: 27,
    title: 'eFeePayment App',
    category: 'Information',
    image: '/images/efeepayment-app.png',
    technology: 'Bootstrap, HTML5, CSS3',
    description: 'eFeePayment ® is an application to make the payment to school by the parents. This application helps to keep the track of payment by the parents and the schools as well. Using this application, a fee of school can be paid in few easy steps.',
  },

];

export default data;
